name: Preprocessing Dataset Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run preprocessing script
        run: |
          python Preprocessing/automate_Muazah.py
      
      - name: Upload preprocessed dataset as artifact
        uses: actions/upload-artifact@v2
        with:
          name: preprocessed-dataset
          path: Dataset/

      - name: Upload MLflow logs
        uses: actions/upload-artifact@v2
        with:
          name: mlruns
          path: mlruns/
